AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'lib/generators/templates/cables/cable.rb'
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 110
  Exclude:
    - 'lib/generators/**/*'
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/ClassVars:
  Exclude:
    - 'lib/get_schwifty.rb'
Metrics/MethodLength:
  Max: 20
Rails/OutputSafety:
  Exclude:
    - 'test/**/*'
