dist: trusty
language: ruby
rvm:
  - "2.4.2"
script:
  - bundle exec rake test
addons:
  chrome: stable
before_install:
  - wget http://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
